//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrdererDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_OrdererDetails()
        {
            this.Tbl_OrderProDetails = new HashSet<Tbl_OrderProDetails>();
        }
    
        public int order_id { get; set; }
        public string order_name { get; set; }
        public Nullable<decimal> order_phone_no { get; set; }
        public string order_add { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> memberID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderProDetails> Tbl_OrderProDetails { get; set; }
        public virtual Tbl_Members Tbl_Members { get; set; }
    }
}
