//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AdminLogin
    {
        public int Admin_id { get; set; }
        public string Admin_UserName { get; set; }
        public string Admin_Password { get; set; }
    }
}
