//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderProDetails
    {
        public int order_p_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_product { get; set; }
        public Nullable<int> order_qty { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public Nullable<decimal> order_t_price { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> memberID { get; set; }
    
        public virtual Tbl_OrdererDetails Tbl_OrdererDetails { get; set; }
        public virtual Tbl_Members Tbl_Members { get; set; }
    }
}
