//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Members()
        {
            this.Tbl_ShippingDetails = new HashSet<Tbl_ShippingDetails>();
            this.Tbl_OrdererDetails = new HashSet<Tbl_OrdererDetails>();
            this.Tbl_OrderProDetails = new HashSet<Tbl_OrderProDetails>();
        }
    
        public int memberID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string UserName { get; set; }
        public string emailID { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string confirmPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ShippingDetails> Tbl_ShippingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrdererDetails> Tbl_OrdererDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderProDetails> Tbl_OrderProDetails { get; set; }
    }
}
